apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-secret
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: '{"auths":{"https://index.docker.io/v1/":{"username":"priyaannamalai","password":"dckr_pat_aH3Lq3w0rZSWoZy0r62y5Ptc7sc"}}}'
