apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: supply-chain-agent
  annotations:
    scenarios.ai.sap.com/description: "Supply Chain AI Agent using Neo4j Graph"
    scenarios.ai.sap.com/name: "supply-chain-agent"
    executables.ai.sap.com/description: "AI Agent that queries Neo4j supply chain graph"
    executables.ai.sap.com/name: "supply-chain-agent-neo4j"
  labels:
    scenarios.ai.sap.com/id: "supply-chain-agent"
    ai.sap.com/version: "1.0.0"
spec:
  inputs:
    parameters: []
  template:
    apiVersion: "serving.kserve.io/v1beta1"
    metadata:
      annotations: |
        autoscaling.knative.dev/metric: concurrency
        autoscaling.knative.dev/target: 1
        autoscaling.knative.dev/targetBurstCapacity: 0
      labels: |
        ai.sap.com/resourcePlan: basic
    spec: |
      predictor:
        imagePullSecrets:
          - name: neo4j
        minReplicas: 1
        maxReplicas: 2
        containers:
        - name: kserve-container
          image: "docker.io/priyaannamalai/neo4j_connect:latest"
          ports:
            - containerPort: 8080
              protocol: TCP
          command: ["/bin/sh", "-c"]
          args:
            - "gunicorn --bind 0.0.0.0:8080 --workers 2 --timeout 120 agent:app"
          env:
            - name: NEO4J_URI
              value: "neo4j+s://59d34f34.databases.neo4j.io"
            - name: NEO4J_USERNAME
              value: "neo4j"
            - name: NEO4J_PASSWORD
              value: "M_GHAzxZtSFPMM2GfBIWhRN-Lk0BlDHxdBQfdPeeZV8"
